version: '3.8'

services:
  comfyui:
    image: qq1151131109/comfyui:latest
    container_name: comfyui
    ports:
      - "8188:8188"
    volumes:
      # 持久化存储
      - ./models:/app/models
      - ./output:/app/output
      - ./input:/app/input
      - ./custom_nodes:/app/custom_nodes
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    environment:
      - PYTHONUNBUFFERED=1
    restart: unless-stopped