from .node import NODE_CLASS_MAPPINGS as NODE_CLASS_MAPPINGS_NODE
from .node import NODE_DISPLAY_NAME_MAPPINGS as NODE_DISPLAY_NAME_MAPPINGS_NODE
from .microsoft_tts import NODE_CLASS_MAPPINGS as NODE_CLASS_MAPPINGS_TTS
from .microsoft_tts import NODE_DISPLAY_NAME_MAPPINGS as NODE_DISPLAY_NAME_MAPPINGS_TTS
from .latentsync_long_video import NODE_CLASS_MAPPINGS as NODE_CLASS_MAPPINGS_LONG
from .latentsync_long_video import NODE_DISPLAY_NAME_MAPPINGS as NODE_DISPLAY_NAME_MAPPINGS_LONG
from .latentsync_adapter import NODE_CLASS_MAPPINGS as NODE_CLASS_MAPPINGS_ADAPTER
from .latentsync_adapter import NODE_DISPLAY_NAME_MAPPINGS as NODE_DISPLAY_NAME_MAPPINGS_ADAPTER

# 合并节点映射
NODE_CLASS_MAPPINGS = {
    **NODE_CLASS_MAPPINGS_NODE, 
    **NODE_CLASS_MAPPINGS_TTS, 
    **NODE_CLASS_MAPPINGS_LONG,
    **NODE_CLASS_MAPPINGS_ADAPTER
}
NODE_DISPLAY_NAME_MAPPINGS = {
    **NODE_DISPLAY_NAME_MAPPINGS_NODE, 
    **NODE_DISPLAY_NAME_MAPPINGS_TTS, 
    **NODE_DISPLAY_NAME_MAPPINGS_LONG,
    **NODE_DISPLAY_NAME_MAPPINGS_ADAPTER
}

__all__ = ['NODE_CLASS_MAPPINGS', 'NODE_DISPLAY_NAME_MAPPINGS'] 